name: 'Build and Deploy eShopOnWeb'

on:
  workflow_run:
    workflows: ['Terraform CI/CD']
    types:
      - completed
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for OIDC authentication

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true

    - name: Build
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - name: Test
      run: dotnet test ./eShopOnWeb.sln --configuration Release --no-build

    - name: Publish Web App
      run: dotnet publish ./src/Web/Web.csproj --configuration Release --no-build --output ./publish/web

    - name: Publish Public API
      run: dotnet publish ./src/PublicApi/PublicApi.csproj --configuration Release --no-build --output ./publish/api

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.7'

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra-tf

    - name: Get Terraform Outputs
      id: terraform
      run: |
        # Get resource group name from Terraform output
        RG_NAME=$(terraform output -raw resource_group_name)
        echo "RESOURCE_GROUP=$RG_NAME" >> $GITHUB_ENV
        
        # Get web app name from Terraform output
        WEBAPP_NAME=$(terraform output -raw web_app_name)
        echo "AZURE_WEBAPP_NAME=$WEBAPP_NAME" >> $GITHUB_ENV
        
        # Get Key Vault URI from Terraform output
        KV_URI=$(terraform output -raw key_vault_uri)
        echo "KEY_VAULT_URI=$KV_URI" >> $GITHUB_ENV
      working-directory: ./infra-tf

    - name: Get Connection Strings
      run: |
        # Get connection strings from Key Vault using the URI from Terraform output
        CATALOG_CONN=$(az keyvault secret show --vault-uri ${{ env.KEY_VAULT_URI }} --name "CatalogConnectionString" --query "value" -o tsv)
        IDENTITY_CONN=$(az keyvault secret show --vault-uri ${{ env.KEY_VAULT_URI }} --name "IdentityConnectionString" --query "value" -o tsv)
        
        # Create publish profile with connection strings for Web App
        cat << EOF > ./publish/web/appsettings.Production.json
        {
          "ConnectionStrings": {
            "CatalogConnection": "$CATALOG_CONN",
            "IdentityConnection": "$IDENTITY_CONN"
          }
        }
        EOF

        # Create publish profile with connection strings for API
        cat << EOF > ./publish/api/appsettings.Production.json
        {
          "ConnectionStrings": {
            "CatalogConnection": "$CATALOG_CONN",
            "IdentityConnection": "$IDENTITY_CONN"
          }
        }
        EOF

    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./publish/web

    - name: Deploy API
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}-api
        package: ./publish/api